### ISSUE TITLE
Problem with Passing iGraph graph objects

### ISSUE THREAD

**Issue by sibinlazarm** [alubbock/microbench#2]
Hai,

Currently I am working with graph and I need to record the performance of the functions available for the specific tasks and choose the best ones for the implementation. But now I got an error when passing the iGraph object to the function under the benchmark decorator.
The error message is : 
Traceback (most recent call last):
  File "C:\Users\sibin\PycharmProjects\dag_bench\benchMarkGraphs.py", line 119, in <module>
    igraph_check_dag(graph_any_ig)
  File "C:\Users\sibin\PycharmProjects\dag_bench\venv\lib\site-packages\microbench\__init__.py", line 182, in inner
    self.output_result(bm_data)
  File "C:\Users\sibin\PycharmProjects\dag_bench\venv\lib\site-packages\microbench\__init__.py", line 142, in output_result
    bm_str = self.to_json(bm_data) + '\n'
  File "C:\Users\sibin\PycharmProjects\dag_bench\venv\lib\site-packages\microbench\__init__.py", line 135, in to_json
    bm_str = '{}'.format(json.dumps(bm_data,
  File "C:\Users\sibin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\sibin\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\sibin\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\sibin\PycharmProjects\dag_bench\venv\lib\site-packages\microbench\__init__.py", line 58, in default
    return super().default(o)
  File "C:\Users\sibin\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Graph is not JSON serializable

Anyone have any solutions for this...?

**Comment by alubbock** [comment]
Hi, the reason for this error is that if you're capturing function arguments (with `MBFunctionCall`) or return values (with `MBReturnValue`), those values need to be encodable to JSON format. The default JSON encoder doesn't handle iGraph objects, hence the error.

I've just released a new version of microbench to PyPI, v0.8, which will skip objects it can't encode with a warning rather than an error, to make it less disruptive. I've also updated the documentation with how to capture custom data types rather than skip them, if that's what you want - see the new [Extending JSONEncoder section in README.md](https://github.com/alubbock/microbench#extending-jsonencoder) for instructions on this.
